- name: Stop Tomcat Service
  hosts: '{{tomcatServerIP}}'
  tasks:
    - name: Stop Service
      service:
        name: '{{ServiceID}}'
        state: stopped
    - name: Copy build to tomcat
      copy:
        src: '{{ApplicationSrcDirs}}'
        dest: '{{tomcatDir}}'
    - name: start Tomcat Service
      service:
        name: '{{ServiceID}}'
        state: started